apiVersion: v1
kind: Service
metadata:
  namespace: tarekchafroud
  labels:
    app: simple-webapp-color
  name: simple-webapp-color
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: simple-webapp-color
  type: ClusterIP
