apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-claim
  namespace: tarekchafroud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
